version: '2.1'
services: 
  config:
    build: config
    ports:
      - 8888:8888
    environment:    
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
  rabbitmq-server:
    build: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
  applications-postgresql:
    restart: always
    image: postgres:9.6.9
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=applications
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
  
  applications-service:
    build: applications-service
    restart: on-failure
    depends_on:
      - config        
      - applications-postgresql  
      - rabbitmq-server
    ports:
      - 8889:8889
