server:
  context-path: /applications
  port: 8889
  
spring:
    rabbitmq:
       host: rabbitmq-server
       port: 5672
       username: guest
       password: guest
    jpa:
        properties:
           hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        show-sql: true
        hibernate.ddl-auto: update
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://applications-postgresql:5432/applications
      username: postgres
      #password: ${POSTGRESQL_PASSWORD}
      password: pgpassword
# Hikari will use the above plus the following to setup connection pooling
      hikari.minimumIdle: 5
      hikari.maximumPoolSize: 20
      hikari.idleTimeout: 30000
      hikari.poolName: SpringBootJPAHikariCP
      hikari.maxLifetime: 2000000
      hikari.connectionTimeout: 30000